language: julia
os:
  - linux
  - osx
julia:
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.test("BusinessDays"; coverage=true)';
  - julia -e 'cd(Pkg.dir("BusinessDays")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())';