language: julia
julia:
  - nightly
notifications:
    email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.checkout("BusinessDays"); Pkg.add("Coverage"); Pkg.checkout("Coverage"); Pkg.test("BusinessDays"; coverage=true)'
after_success:
  - echo $REPO_TOKEN
  - julia -e 'cd(Pkg.dir("BusinessDays")); using Coverage; Codecov.submit(Codecov.process_folder())'