language: julia
julia:
  - nightly
notifications:
    email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.checkout("BusinessDays"); Pkg.clone("https://github.com/felipenoris/Coverage.jl.git"); Pkg.checkout("Coverage", "codecovsubmit") Pkg.test("BusinessDays"; coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("BusinessDays")); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'cd(Pkg.dir("BusinessDays")); using Coverage; Codecov.submit(Codecov.process_folder())'